sources:
  - name: my_airbnb
    schema: RAW_AIRBNB
    tables:
      - name: my_listings
        identifier: listings
        columns:
          - name: room_type
            description: "Type of room being listed."
            data_tests:
              - dbt_expectations.expect_column_distinct_count_to_equal:
                  arguments:
                    value: 4
          - name: price
            description: "Price of the listing."
            data_tests:
              - dbt_expectations.expect_column_values_to_match_regex:
                  arguments:
                    regex: '^\\$[0-9][0-9\\.]'
      - name: my_hosts
        identifier: hosts
      - name: my_reviews
        identifier: reviews